### ISSUE TITLE
Cannot compile with OSX

### ISSUE THREAD

**Issue by mdering** [mynameisfiber/pyxmeans#6] opened 2015-01-19 17:03 UTC
this will not compile and run on OSX mavericks. I've told it to use GCC 4.9 installed from homebrew, but when it links it gives the error 
duplicate symbol _distance_metric in: 
build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/distance.o

and 

duplicate symbol _distance_metric in:
build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
 build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/minibatch.o

**Comment by mynameisfiber** [comment] 2015-01-19 17:33
Can you give me the full output of `gcc --version`, `ld --version` and `python setup.py build`?  I have gcc 4.9.1 and it seems to be working just fine.

**Comment by mdering** [comment] 2015-01-19 17:46
for `gcc` I have 

```gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1     
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)     
Target: x86_64-apple-darwin14.1.0     
Thread model: posix```


for gcc-4.9 which i set in the setup script using os.environ i have
    ` gcc-4.9 (Homebrew gcc 4.9.2_1 --without-multilib) 4.9.2
     Copyright (C) 2014 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

for ld i get 

     ld: unknown option: --version

and (sorry markdown isnt working here) for python setup.py build. Any ideas?

```running build
running build_py
running build_ext
building 'pyxmeans._minibatch' extension
C compiler: gcc-4.9 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

compile options: '-I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
extra options: '-O3 -std=c99 -fopenmp -Wall -p -pg'
gcc-4.9: pyxmeans/c_minibatch/minibatch.c
gcc-4.9: pyxmeans/c_minibatch/distance.c
gcc-4.9: pyxmeans/_minibatch.c
In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pyxmeans/_minibatch.c:2:
/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
pyxmeans/_minibatch.c:490:5: warning: initialization from incompatible pointer type
     {"minibatch"        , py_minibatch        , METH_VARARGS , minibatch_docstring        }  , 
     ^
pyxmeans/_minibatch.c:490:5: warning: (near initialization for 'module_methods[0].ml_meth')
pyxmeans/_minibatch.c:491:5: warning: initialization from incompatible pointer type
     {"minibatch_multi"  , py_minibatch_multi  , METH_VARARGS , minibatch_multi_docstring  }  , 
     ^
pyxmeans/_minibatch.c:491:5: warning: (near initialization for 'module_methods[1].ml_meth')
pyxmeans/_minibatch.c:492:5: warning: initialization from incompatible pointer type
     {"assign_centroids" , py_assign_centroids , METH_VARARGS , assign_centroids_docstring }  , 
     ^
pyxmeans/_minibatch.c:492:5: warning: (near initialization for 'module_methods[2].ml_meth')
pyxmeans/_minibatch.c:493:5: warning: initialization from incompatible pointer type
     {"kmeanspp"         , py_kmeanspp         , METH_VARARGS , kmeanspp_docstring         }  , 
     ^
pyxmeans/_minibatch.c:493:5: warning: (near initialization for 'module_methods[3].ml_meth')
pyxmeans/_minibatch.c:494:5: warning: initialization from incompatible pointer type
     {"kmeanspp_multi"   , py_kmeanspp_multi   , METH_VARARGS , kmeanspp_multi_docstring   }  , 
     ^
pyxmeans/_minibatch.c:494:5: warning: (near initialization for 'module_methods[4].ml_meth')
gcc-4.9: pyxmeans/c_minibatch/generate_data.c
gcc-4.9 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/distance.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/generate_data.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/minibatch.o -o build/lib.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.so -lgomp -lc -lm
duplicate symbol _distance_metric in:
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/distance.o
duplicate symbol _distance_metric in:
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/minibatch.o
ld: 2 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
duplicate symbol _distance_metric in:
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/distance.o
duplicate symbol _distance_metric in:
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o
    build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/minibatch.o
ld: 2 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
error: Command "gcc-4.9 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/distance.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/generate_data.o build/temp.macosx-10.10-x86_64-2.7/pyxmeans/c_minibatch/minibatch.o -o build/lib.macosx-10.10-x86_64-2.7/pyxmeans/_minibatch.so -lgomp -lc -lm" failed with exit status 1```

**Comment by mynameisfiber** [comment] 2015-01-19 17:59
Try doing a `brew install binutils` (or whatever the brew command is to upgrade it).

**Comment by mdering** [comment] 2015-01-19 18:05
looks like the same thing happened.

**Comment by pliskowski** [comment] 2015-01-20 13:11
Interestingly, I experience the same problem on OSX. Building with brewed gcc49. Tried also with gcc49 from http://hpc.sourceforge.net. Same thing.

**Comment by mynameisfiber** [comment] 2015-01-20 14:48
Yea... I'm guessing it has to do with the linker the OSX is using.  I'm on linux so I can't easily debug this problem.  Can you try building the code in osx branch from the pull request?

**Comment by mdering** [comment] 2015-01-20 14:53
looks like the exact same issue, duplicate symbols. Its interesting cause doing a make on the c code provided compiles ok.

**Comment by mynameisfiber** [comment] 2015-01-20 15:02
Yea, the problem is that both the c module and the c-python glue need to include `distance.h` which defines `distance_metric`.  This means in the end the code'll see two definitions of it once linked and the new OSX linker cares about this while other linkers think it's OK.

**Comment by mdering** [comment] 2015-01-20 15:17
It looks like other people have reported this same problem in OSX. It did work for me on linux.

**Comment by pliskowski** [comment] 2015-01-20 21:49
I can confirm it works on linux box. However, the above fix for OSX didn't work for me.

**Comment by pliskowski** [comment] 2015-01-27 19:51
@mynameisfiber any tips on how this could be fixed on OSX? Cheers

**Closed** 2022-11-22 18:22 UTC
